### ISSUE TITLE
Unit tests fail (randomly?)

### ISSUE THREAD

**Issue by salamanders** [EdwardRaff/JSAT#17]
I ran the unit tests a few times in a row, and each time, a different set of 1 to 3 of them failed.

testTrainC_ClassificationDataSet(jsat.classifiers.trees.RandomForestTest)  Time elapsed: 0.242 sec  <<< FAILURE!
testSearch_Vec_int(jsat.linear.vectorcollection.RandomBallCoverTest)  Time elapsed: 0.013 sec  <<< FAILURE!

**Comment by EdwardRaff** [comment]
Was this with the head in github or with the 0.0.2 release?

**Comment by salamanders** [comment]
Head.

**Comment by EdwardRaff** [comment]
What was the 3rd test that failed? RBC and RF shouldn't fail any more in head. RF was a matter of RF sometimes dosn't generalize great, RBC appears to maybe be an issue with the published algorithm.

**Comment by salamanders** [comment]
Better now after a pull!

jsat.classifiers.boosting.StackingTest
java.lang.AssertionError: expected:<0.0> but was:<0.10811871361598667>

jsat.math.FastMathTest
java.lang.AssertionError at jsat.math.FastMathTest.testPow(FastMathTest.java:152)

**Comment by TKlerx** [comment]
I also ran some tests with the current master branch and aggregated the (not yet mentioned) failures and errors I found on various systems:

```
java.lang.AssertionError: jsat.linear.vectorcollection.VPTreeMV$VPTreeMVFactory failed expected:<97> but was:<95>
	at jsat.linear.vectorcollection.VPTreeMVTest.testSearch_Vec_double(VPTreeMVTest.java:114)
	
java.lang.AssertionError: jsat.linear.vectorcollection.VPTreeMV$VPTreeMVFactory failed expected:<67> but was:<64>
	at jsat.linear.vectorcollection.VPTreeMVTest.testSearch_Vec_double(VPTreeMVTest.java:114)

	java.lang.AssertionError: jsat.linear.vectorcollection.VPTreeMV$VPTreeMVFactory failed 4
	at jsat.linear.vectorcollection.VPTreeMVTest.testSearch_Vec_int(VPTreeMVTest.java:171)

java.lang.NullPointerException
	at jsat.linear.vectorcollection.VPTreeMVTest.testSearch_Vec_int(VPTreeMVTest.java:156)
	
	
java.lang.NullPointerException
	at jsat.linear.vectorcollection.VPTreeTest.testSearch_Vec_int(VPTreeTest.java:152)

java.lang.AssertionError: jsat.linear.vectorcollection.VPTree$VPTreeFactory failed expected:<67> but was:<66>
	at jsat.linear.vectorcollection.VPTreeTest.testSearch_Vec_double(VPTreeTest.java:113)

java.lang.AssertionError: jsat.linear.vectorcollection.VPTree$VPTreeFactory failed 2
	at jsat.linear.vectorcollection.VPTreeTest.testSearch_Vec_int(VPTreeTest.java:167)


java.lang.AssertionError: expected:<0.5> but was:<0.7592323750864884>
	at jsat.classifiers.calibration.PlattCalibrationTest.testTrain(PlattCalibrationTest.java:91)

java.lang.AssertionError
	at jsat.classifiers.linear.LinearBatchTest.testTrainWarmCMultieFast(LinearBatchTest.java:175)
	
java.lang.AssertionError: expected:<4> but was:<5>
	at jsat.clustering.kmeans.GMeansTest.testCluster_3args_1_findK(GMeansTest.java:86)

java.lang.AssertionError: expected:<0.0> but was:<0.010000000000000009>
	at jsat.classifiers.linear.kernelized.BOGDTest.testTrainC_ClassificationDataSet(BOGDTest.java:93)

java.lang.AssertionError
	at jsat.regression.NadarayaWatsonTest.testTrainC_RegressionDataSet_ExecutorService(NadarayaWatsonTest.java:103)
```

I hope this helps and I don't bug you again ;)

**Comment by EdwardRaff** [comment]
Note a problem! Thanks for the reports!

Can you include stack traces/line numbers for the ones that gave null-pointer exceptions?

**Comment by TKlerx** [comment]
```
java.lang.NullPointerException
	at jsat.linear.vectorcollection.VPTree$VPNode.searchKNN(VPTree.java:463)
	at jsat.linear.vectorcollection.VPTree$VPNode.searchKNN(VPTree.java:455)
	at jsat.linear.vectorcollection.VPTree$VPNode.searchKNN(VPTree.java:463)
	at jsat.linear.vectorcollection.VPTree$VPNode.searchKNN(VPTree.java:463)
	at jsat.linear.vectorcollection.VPTree$VPNode.searchKNN(VPTree.java:463)
	at jsat.linear.vectorcollection.VPTree$VPNode.searchKNN(VPTree.java:463)
	at jsat.linear.vectorcollection.VPTree.search(VPTree.java:181)
	at jsat.linear.vectorcollection.VPTreeMVTest.testSearch_Vec_int(VPTreeMVTest.java:156)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at jsat.classifiers.ClassificationDataSet.<init>(ClassificationDataSet.java:102)
	at jsat.classifiers.neuralnetwork.LVQLLC.trainC(LVQLLC.java:211)
	at jsat.classifiers.ClassificationModelEvaluation.evaluationWork(ClassificationModelEvaluation.java:293)
	at jsat.classifiers.ClassificationModelEvaluation.evaluateTestSet(ClassificationModelEvaluation.java:269)
	at jsat.classifiers.neuralnetwork.LVQLLCTest.testTrainC_ClassificationDataSet_ExecutorService(LVQLLCTest.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

java.lang.NullPointerException
	at jsat.linear.vectorcollection.VPTree$VPNode.searchKNN(VPTree.java:458)
	at jsat.linear.vectorcollection.VPTree$VPNode.searchKNN(VPTree.java:458)
	at jsat.linear.vectorcollection.VPTree$VPNode.searchKNN(VPTree.java:463)
	at jsat.linear.vectorcollection.VPTree$VPNode.searchKNN(VPTree.java:455)
	at jsat.linear.vectorcollection.VPTree$VPNode.searchKNN(VPTree.java:463)
	at jsat.linear.vectorcollection.VPTree$VPNode.searchKNN(VPTree.java:463)
	at jsat.linear.vectorcollection.VPTree.search(VPTree.java:181)
	at jsat.linear.vectorcollection.VPTreeTest.testSearch_Vec_int(VPTreeTest.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

I also found other failing tests. Are you still interested in the exceptions only or also in the failures?
Sometimes I discover new failures and exceptions, I could put them into some document. I think this bug report is sort of confusing when gathering failures and exceptions.

**Comment by EdwardRaff** [comment]
I can't get any of the VP cases to fail. What hardware/ Java Versions are you using? 

The "Warm" tests may be problematic... since their passing is somewhat performance based. I'll think on that one.

**Comment by TKlerx** [comment]
It's my notebook again (remember, when you tried to reconstruct the bugs remotely?).
Some old dual core, Fedora 22, eclipse compiler and OpenJDK 1.8.60

I guess there is some strange bug that is caused by some random initialization that does not occur on other systems. 
On my VM with the same software (Fedora, eclipse, openJDK) only one of those exceptions occurs - sometimes even all tests pass.
I assume that it is because of the old CPU and only two cores. I observed that the more CPU cores you have the less tests fail.

It may be that it also depends on the order in which the tests are executed. If I just run the single test that throws an exception it always passes. The exceptions only occur if I run all tests together.

**Comment by EdwardRaff** [comment]
Can you test with Oracle JDK? 

If we could isolate this issue and fix it or open a bug report up stream that would be awesome - but this is some weird bug combination :-/

**Comment by TKlerx** [comment]
Ok, I reran the tests with the current Oracle JDK (1.8.65), Fedora 22, Eclipse 4.5.1 and I got 3 exceptions after 5 runs (even a new one; see the google doc for the stack trace and a screenshot).

```
java.lang.NullPointerException
	at jsat.linear.vectorcollection.VPTreeMVTest.testSearch_Vec_int(VPTreeMVTest.java:156)

java.lang.ArithmeticException: Can not add a value Infinity
	jsat.datatransform.visualization.IsomapTest.testTransform_DataSet_ExecutorService(IsomapTest.java:127)

java.lang.NullPointerException
	at jsat.linear.vectorcollection.VPTreeTest.testSearch_Vec_int(VPTreeTest.java:152)
```

**Comment by EdwardRaff** [comment]
Hmm, I'll try and set up a VM later and only give it 2 cores to see if I can reproduce the VP failures. Very strange.

**Comment by TKlerx** [comment]
Forgot to mention that everything is x64 and I have 4 GB RAM on my notebook.

**Comment by EdwardRaff** [comment]
@TKlerx  please pull from head and confirm that VP trees no longer fail! 

@salamanders could you indicate exactly which test is failing for Stacking?

**Comment by TKlerx** [comment]
Looks good! Nice job! No more VP tree exceptions with Oracle JDK or OpenJDK.
The only exception I still get is:
```
java.lang.ArithmeticException: Can not add a value Infinity
    at jsat.linear.Matrix.increment(Matrix.java:552)
    at jsat.datatransform.visualization.MDS.transform(MDS.java:262)
    at jsat.datatransform.visualization.Isomap.transform(Isomap.java:312)
    at jsat.datatransform.visualization.IsomapTest.testTransform_DataSet_ExecutorService(IsomapTest.java:127)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**Comment by norvar** [comment]
I had 3 testing errors. 

OS: Win 10

E:\data\finance\docs\ML\lib\JSAT-master\JSAT>java -version
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)

E:\data\finance\docs\ML\lib\JSAT-master\JSAT>javac -version
javac 1.7.0_79

Results :

Failed tests:
  LinearBatchTest.testTrainWarmCMultieFast:175 Warm start wasn't faster? 30 vs 28
  FastMathTest.testPow:152 null
  NadarayaWatsonTest.testTrainC_RegressionDataSet_ExecutorService:103 null

Tests run: 1049, Failures: 3, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:28 min
[INFO] Finished at: 2016-01-04T16:59:37-05:00
[INFO] Final Memory: 9M/244M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project JSAT: There are test failures.
[ERROR]
[ERROR] Please refer to E:\data\finance\docs\ML\lib\JSAT-master\JSAT\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project JSAT: There are test failures.

Please refer to E:\data\finance\docs\ML\lib\JSAT-master\JSAT\target\surefire-reports for the individual test results.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

Please refer to E:\data\finance\docs\ML\lib\JSAT-master\JSAT\target\surefire-reports for the individual test results.
        at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution(SurefireHelper.java:82)
        at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary(SurefirePlugin.java:254)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:854)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:722)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
