### ISSUE TITLE
3 test erros.

### ISSUE THREAD

**Issue by norvar** [EdwardRaff/JSAT#31]
I had 3 test errors.

OS: Win 10

E:\data\finance\docs\ML\lib\JSAT-master\JSAT>java -version
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)

E:\data\finance\docs\ML\lib\JSAT-master\JSAT>javac -version
javac 1.7.0_79

Results :

Failed tests:
LinearBatchTest.testTrainWarmCMultieFast:175 Warm start wasn't faster? 30 vs 28
FastMathTest.testPow:152 null
NadarayaWatsonTest.testTrainC_RegressionDataSet_ExecutorService:103 null

Tests run: 1049, Failures: 3, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:28 min
[INFO] Finished at: 2016-01-04T16:59:37-05:00
[INFO] Final Memory: 9M/244M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project JSAT: There are test failures.
[ERROR]
[ERROR] Please refer to E:\data\finance\docs\ML\lib\JSAT-master\JSAT\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project JSAT: There are test failures.

Please refer to E:\data\finance\docs\ML\lib\JSAT-master\JSAT\target\surefire-reports for the individual test results.
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

Please refer to E:\data\finance\docs\ML\lib\JSAT-master\JSAT\target\surefire-reports for the individual test results.
at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution(SurefireHelper.java:82)
at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary(SurefirePlugin.java:254)
at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:854)
at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:722)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
... 20 more

**Comment by EdwardRaff** [comment]
Don't worry about the `LinearBatchTest.testTrainWarmCMultieFast` error, all the warm-start tests need to be improved. 

I'll look into the other two. What version of JSAT was this with?

**Comment by norvar** [comment]
Newest download. 

Sorry for replying late. I was out of town to Princeton. 

I am new to JSAT.  I didn't find any generated jar files. So how do I use your algorithms in my project normally?  

Thanks.

**Comment by EdwardRaff** [comment]
Jars are in maven and the release tab. You can tell make to skip tests as well. 

Please see the examples in the wiki, as linked on the project page.

**Comment by norvar** [comment]
I didn't find a way to skip the tests in your wiki.

**Comment by EdwardRaff** [comment]
Its a maven project, I wouldn't document how to skip tests for maven in my project.

**Comment by norvar** [comment]
OK. I misunderstood. Thanks.

**Comment by norvar** [comment]
Just run the following in case someone wants to know:
>mvn install -DskipTests

**Comment by EdwardRaff** [comment]
I don't think any of these fail now (just did a number of commits to improve reliability of unit tests), so I'm closing this issue
